-- 
-- Raw data table for this source
--

SET search_path TO :sch;

DROP TABLE IF EXISTS "ntt_species_raw";
CREATE TABLE "ntt_species_raw" (
"SppID" bigint,
"Family" text,
"Genus" text,
"Species" text,
"Species code" text,
"Growth habits" text,
"Potential height" text,
"Mesoamerica " text,
"Caribbean" text,
"Los Llanos" text,
"Amazonia " text,
"Cerrado" text,
"Caatinga " text,
"Atlantic Forest" text,
"Pampa" text,
"Gran Chaco" text,
"Patagonia" text,
"Northern Andean" text,
"Southern Andean" text,
"Peruvian-Chilean Desert " text,
"Mediterranean Chile" text,
"Temperate Pacific " text,
"Insular Pacific" text,
"Equatorial" text,
"Tropical " text,
"Subtropical " text,
"Temperate" text,
"Subantarctic" text,
"Rain forest " text,
"Cloud forest" text,
"Mixed forest" text,
"Semideciduous forest " text,
"Deciduous forest" text,
"Evergreen seasonal forest" text,
"Evergreen floodplain forest" text,
"Seasonal floodplain forest " text,
"Seasonal riverine forest" text,
"Montane woodland" text,
"Coastal sandy mosaic " text,
"Savanna woodland" text,
"White-sand woodland" text,
"Rocky woodland " text,
"Semi-arid thorny woodland" text,
"Semi-desert and Desert" text,
"Adventitious" text,
"South Florida" text,
"Mexico" text,
"Belize" text,
"Guatemala" text,
"El Salvador " text,
"Honduras " text,
"Nicaragua" text,
"Costa Rica" text,
"Panama" text,
"Isla del Coco" text,
"Galapagos" text,
"Jamaica" text,
"Cuba" text,
"Hispaniola" text,
"Puerto Rico " text,
"Bahamas" text,
"Lesser Antilles" text,
"Trinidad and Tobago" text,
"French Guiana" text,
"Surinam" text,
"Guyana" text,
"Venezuela" text,
"Colombia " text,
"Ecuador" text,
"Peru" text,
"Bolivia" text,
"Paraguay " text,
"Uruguay" text,
"Argentina" text,
"Chile" text,
"Juán Fernández " text,
"Brasil" text,
"Rondonia " text,
"Acre" text,
"Amazonas " text,
"Roraima" text,
"Pará" text,
"Amapá" text,
"Tocantins" text,
"Maranhão " text,
"Piauí" text,
"Ceará" text,
"Rio Grande do Norte" text,
"Fernando de Noronha" text,
"Paraíba" text,
"Pernambuco" text,
"Alagoas" text,
"Sergipe" text,
"Bahia" text,
"Minas Gerais" text,
"Espírito Santo " text,
"Rio de Janeiro " text,
"São Paulo" text,
"Paraná" text,
"Santa Catarina " text,
"Rio Grande do Sul " text,
"Mato Grosso do Sul" text,
"Mato Grosso " text,
"Goiás" text,
"Distrito Federal" text,
"Main source" text,
"Selection cells" text,
"Date of last change" text
); 

DROP TABLE IF EXISTS "ntt_areas_raw";
CREATE TABLE "ntt_areas_raw" (
"AreaID" bigint,
"SelectionCells" text,
"AreaCode" text,
"SiteName" text,
"Country" text,
"State/Province" text,
"Latitude" text,
"Longitude" text,
"Lat10" text,
"Long10" text,
"Altitude" text,
"Alt SRTM" text,
"Domain" text,
"DomN" text,
"EcoUnit" text,
"FitGeoN" text,
"Asp Ocean" text,
"Thermic realm" text,
"Elevation range" text,
"Zonal Azonal" text,
"Climatic regime" text,
"Leaf flush" text,
"Vegetation physiognomy" text,
"Vegetation type" text,
"CdVg" text,
"Main vegetation type" text,
"TempCorrection" text,
"PrecipCorrection" text,
"TempAnn" text,
"TempDayRng" text,
"Isotherm" text,
"TempSeas" text,
"TempMax" text,
"TempMin" text,
"TempAnnRng" text,
"PrecAnn" text,
"PrecWetP" text,
"PrecDryP" text,
"PrecSeas" text,
"WaterDefDur" text,
"WaterDefSev" text,
"WaterExcDur" text,
"WaterExcSev" text,
"HyperSeas" text,
"DaysFrost" text,
"CloudItcp" text,
"Grassy Cover" text,
"Surface Rockiness" text,
"Ranked Rockiness" text,
"Soil Texture Class" text,
"Ranked Sand" text,
"Soil Drainage Class" text,
"Ranked Drainage" text,
"Soil Water Storage" text,
"Soil Fertility Class" text,
"Ranked TBS" text,
"Salinity Class" text,
"Ranked Salinity" text
); 

DROP TABLE IF EXISTS "ntt_sources_raw";
CREATE TABLE "ntt_sources_raw" (
"RefID" bigint,
"References" text
); 

DROP TABLE IF EXISTS "ntt_species_areas_raw";
CREATE TABLE "ntt_species_areas_raw" (
"AreaID" bigint,
"SppID" bigint
); 

-- text data type allows NULLs
-- These will be deleted later and type changed to bigint
DROP TABLE IF EXISTS "ntt_sources_areas_raw";
CREATE TABLE "ntt_sources_areas_raw" (
"AreaID" bigint,
"RefID" text
); 