
-- --------------------------------------------------------------
-- Insert raw data to staging table
-- 
-- NOTE: This script is source-specific
-- --------------------------------------------------------------

SET search_path TO :sch;

INSERT INTO vfoi_staging (
observation_type,
plot_metadata_id,
datasource_id,
datasource,
dataset,
dataowner,
country_verbatim,
state_province_verbatim,
county_verbatim,
country,
state_province,
county,
locality,
latlong_verbatim,
latitude,
longitude,
geodeticDatum,
coord_uncertainty_m,
coord_uncertainty_verbatim,
coord_max_uncertainty_km,
georef_sources,
georef_protocol,
is_in_country,
is_in_state_province,
is_in_county,
is_geovalid,
is_new_world,
project_id,
project_contributors,
location_id,
plot_name,
subplot,
is_location_cultivated,
locationevent_id,
event_date,
event_date_accuracy,
elevation_verbatim,
elevation_m,
slope_aspect_deg,
slope_gradient_deg,
plot_area_ha,
sampling_protocol,
temperature_c,
precip_mm,
stratum_name,
vegetation_verbatim,
community_concept_name,
observation_contributors,
custodial_institution_codes,
collection_code,
catalog_number,
occurrence_id,
recorded_by,
record_number,
date_collected,
date_collected_accuracy,
identified_by,
date_identified,
date_identified_accuracy,
identification_remarks,
bien_taxonomy_id,
taxon_id,
family_taxon_id,
genus_taxon_id,
species_taxon_id,
verbatim_family,
verbatim_scientific_name,
name_submitted,
fk_tnrs_id,
family_matched,
name_matched,
name_matched_author,
tnrs_name_matched_score,
tnrs_warning,
matched_taxonomic_status,
scrubbed_taxonomic_status,
higher_plant_group,
scrubbed_family,
scrubbed_genus,
scrubbed_specific_epithet,
scrubbed_species_binomial,
scrubbed_taxon_name_no_author,
scrubbed_taxon_canonical,
scrubbed_author,
scrubbed_taxon_name_with_author,
scrubbed_species_binomial_with_morphospecies,
growth_form,
reproductive_condition,
occurrence_remarks,
taxon_observation_id,
taxon_name_usage_concept_author_code,
plantobservation_id,
aggregate_organism_observation_id,
individual_organism_observation_id,
individual_id,
individual_count,
cover_percent,
cites,
iucn,
usda_federal,
usda_state,
is_embargoed_observation,
geom,
nsr_id,
native_status_country,
native_status_state_province,
native_status_county_parish,
native_status,
native_status_reason,
native_status_sources,
isintroduced,
is_cultivated_in_region,
citation_verbatim,
citation,
is_new,
is_cultivated_observation,
is_cultivated_observation_basis
) 
SELECT
'checklist occurrence',
NULL,
NULL,
:'src',
:'src',
:'src',
"Country",
"State/Province",
NULL,
NULL,
NULL,
NULL,
"SiteName",
CONCAT_WS(', ',"Latitude","Longitude"),
case
when "Lat10"='' then null
else cast("Lat10" as numeric)
end,
case
when "Long10"='' then null
else cast("Long10" as numeric)
end,
NULL,
5000,
NULL,
5,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
1,
NULL,
NULL,
NULL,
"AreaCode",
NULL,
NULL,
NULL,
NULL,
NULL,
"Altitude",
case
when "Altitude" is null or trim("Altitude")='' THEN null
else cast("Altitude" as numeric)
end,
NULL,
NULL,
7850,
'All species recorded in a circle of 5 km radius, centered on the geocoordinates given above',
case
when "TempAnn"='' then null
else cast("TempAnn" as numeric(4,1))
end,
case
when "PrecAnn"='' then null
else cast("PrecAnn" as numeric(6,1))
end,
NULL,
"Vegetation type",
array["Vegetation type"],
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Family",
"Species",
TRIM(CONCAT_WS(' ',"Family","Species")),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Growth habits",
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
"Main source",
NULL,
1,
0,
'Source database'
FROM ntt_species_raw s JOIN ntt_species_areas_raw sa
ON s."SppID"=sa."SppID"
JOIN ntt_areas_raw a
ON sa."AreaID"=a."AreaID"
:limit
;

