-- ---------------------------------------------------------
-- Copy table & contents, stripping indexes
-- ---------------------------------------------------------

SET search_path TO :dev_schema;

ALTER TABLE :dev_schema.analytical_stem RENAME TO analytical_stem_temp;

DROP TABLE IF EXISTS :dev_schema.analytical_stem;
CREATE TABLE :dev_schema.analytical_stem AS 
SELECT 
analytical_stem_id,
datasource_id,
datasource,
dataset,
dataowner,
plot_metadata_id,
plot_name,
plantobservation_id,
taxonobservation_id,
country,
state_province,
county,
locality,
latitude,
longitude,
coord_uncertainty_m,
georef_sources,
georef_protocol,
is_geovalid,
is_new_world,
project_id,
project_contributors,
location_id,
subplot,
is_location_cultivated,
locationevent_id,
event_date,
elevation_m,
slope_aspect_deg,
slope_gradient_deg,
plot_area_ha,
sampling_protocol,
temperature_c,
precip_mm,
stratum_name,
community_concept_name,
observation_contributors,
custodial_institution_codes,
collection_code,
catalog_number,
occurrence_id,
recorded_by,
record_number,
date_collected,
identified_by,
date_identified,
identification_remarks,
bien_taxonomy_id,
verbatim_family,
verbatim_scientific_name,
name_submitted,
family_matched,
name_matched,
name_matched_author,
tnrs_warning,
matched_taxonomic_status AS taxonomic_status,
matched_taxonomic_status,
higher_plant_group,
scrubbed_family,
scrubbed_genus,
scrubbed_specific_epithet,
scrubbed_species_binomial,
scrubbed_taxon_name_no_author,
scrubbed_taxon_canonical,
scrubbed_author,
scrubbed_taxon_name_with_author,
scrubbed_species_binomial_with_morphospecies,
scrubbed_taxonomic_status,
growth_form,
reproductive_condition,
is_cultivated,
is_cultivated_basis,
occurrence_remarks,
cover_percent,
taxon_observation_id,
taxon_name_usage_concept_author_code,
aggregate_organism_observation_id,
individual_organism_observation_id,
individual_id,
individual_count,
tag,
relative_x_m,
relative_y_m,
stem_code,
stem_dbh_cm,
stem_height_m
FROM :dev_schema.analytical_stem_temp
;

DROP TABLE IF EXISTS :dev_schema.analytical_stem_temp;
