-- 
-- Load plot metadata to staging table
--

SET search_path TO :sch;

INSERT INTO plot_metadata_staging (
datasource,
dataset,
dataowner,
primary_dataowner_email,
plot_name,
plot_name_full,
country_verbatim,
state_province_verbatim,
county_verbatim,
country,
state_province,
county,
locality,
latlong_verbatim,
latitude,
longitude,
geodeticdatum,
coord_uncertainty_m,
coord_uncertainty_verbatim,
coord_max_uncertainty_km,
georef_sources,
georef_protocol,
is_centroid,
is_in_country,
is_in_state_province,
is_in_county,
is_geovalid,
is_new_world,
event_date,
event_date_accuracy,
elevation_m,
slope_aspect_deg,
slope_gradient_deg,
temperature_c,
precip_mm,
community_concept_name,
plot_area_ha,
sampling_protocol,
plot_metadata_id,
datasource_id,
datasource_plot_id,
abundance_measurement,
abundance_measurement_description,
has_strata,
has_stem_data,
methodology_reference,
methodology_description,
stem_diam_min,
stem_diam_min_units,
stem_diam_max,
stem_diam_max_units,
stem_measurement_height,
stem_measurement_height_units,
growth_forms_included_all,
growth_forms_included_trees,
growth_forms_included_shrubs,
growth_forms_included_lianas,
growth_forms_included_herbs,
growth_forms_included_epiphytes,
growth_forms_included_notes,
taxa_included_all,
taxa_included_seed_plants,
taxa_included_ferns_lycophytes,
taxa_included_bryophytes
) 
SELECT
:'src',
:'src',
:'src',
NULL,
"plot_code",
"plot_full_name",
"country",
"state",
"pol2",
NULL,
NULL,
NULL,
"locality_description",
concat_ws(', ',"lat_dec","long_dec"),
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
CASE 
WHEN "elev_m"='coastal woodland' THEN 0::integer
WHEN "elev_m"~E'^\\d+$' THEN "elev_m"::integer 
ELSE null 
END,
NULL,
NULL,
CASE 
WHEN "mean_ann_temp_c"~E'^\\d+$' THEN "mean_ann_temp_c"::integer ELSE NULL 
END,
CASE 
WHEN "tot_ann_precip_mm"~E'^\\d+$' THEN "tot_ann_precip_mm"::integer ELSE NULL 
END,
NULL,
case
when "plot_area_ha" is null or "plot_area_ha"='' then null
else cast("plot_area_ha" as double precision)
end,
'0.1 ha  transect, stems >= 2.5 cm dbh',
NULL,
NULL,
NULL,
'individuals',
NULL,
'no',
'yes',
"plot_notes",
'0.1 ha  transect, stems >= 2.5 cm dbh',
2.5,
'cm',
NULL,
NULL,
NULL,
NULL,
NULL,
'yes',
'yes',
'yes',
'no',
'no',
'Growths forms included determined by stem size cutoff. Wody epiphtyes and both woody and herbaceous epiphytes included if stem or aerial root diameters >= min stem diameter at breast height',
NULL,
'yes',
'yes',
'no'
FROM :"tbl_plot_metadata"