-- --------------------------------------------------------
-- Creates main traits table & raw trait data import table
-- --------------------------------------------------------

set search_path to :dev_schema;

-- Main trait table
DROP TABLE IF EXISTS agg_traits;
CREATE TABLE agg_traits (
id serial primary key not null,
traits_id integer default null,
verbatim_family text default null,
verbatim_scientific_name text default null,
name_submitted text default null,
family_matched text default null,
name_matched text default null,
name_matched_author text default null,
higher_plant_group text default null,
tnrs_warning text default null,
matched_taxonomic_status text default null,
scrubbed_taxonomic_status text default null,
scrubbed_family text default null,
scrubbed_genus text default null,
scrubbed_specific_epithet text default null,
scrubbed_species_binomial text default null,
scrubbed_taxon_name_no_author text default null,
scrubbed_taxon_canonical text default null,
scrubbed_author text default null,
scrubbed_taxon_name_with_author text default null,
scrubbed_species_binomial_with_morphospecies text default null,
trait_name text default null,
trait_value text default null,
unit text default null,
method text default null,
region text default null,
country text default null,
stateprovince text default null,
lower_political text default null,
locality_description text default null,
latitude text default null,
longitude text default null,
min_latitude text default null,
max_latitude text default null,
elevation text default null,
source text default null,
url_source text default null,
source_citation text default null,
source_id text default null,
visiting_date text default null,
reference_number text default null,
access text default null,
project_pi text default null,
project_pi_contact text default null,
observation text default null,
authorship text default null,
authorship_contact text default null,
citation_bibtex text default null,
plant_trait_files text default null
);

-- Raw trait data table
DROP TABLE IF EXISTS traits_raw;
CREATE TABLE traits_raw (
family text default null,
genus text default null,
species text default null,
intraspecific_rank text default null,
varsubsp text default null,
taxon text default null,
authority text default null,
trait_name text default null,
trait_value text default null,
unit text default null,
method text default null,
region text default null,
country text default null,
stateprovince text default null,
lower_political text default null,
locality_description text default null,
latitude text default null,
min_latitude text default null,
max_latitude text default null,
longitude text default null,
min_longitude text default null,
max_longitude text default null,
elevation text default null,
source text default null,
url_source text default null,
source_citation text default null,
source_id text default null,
visiting_date text default null,
reference_number text default null,
access text default null,
project_pi text default null,
project_pi_contact text default null,
observation text default null,
authorship text default null,
authorship_contact text default null,
traits_id text default null,
id text default null,
citation_bibtex text default null,
plant_trait_files text default null
);