-- ---------------------------------------------------------
-- Test version. Ensures equal numbers of specimen and plot
-- observations
-- ---------------------------------------------------------

-- SET search_path TO analytical_db_dev, postgis;
-- postgis included to enable geospatial columns
SET search_path TO :target_schema, postgis;

BEGIN;

LOCK TABLE :src_schema.view_full_occurrence_individual IN SHARE MODE;

-- Adjust work_mem, but research carefully
-- SET LOCAL work_mem = '500 MB';  -- just for this transaction

-- Generate the first temp table, adding and populating the
-- new columns in position desired. Be sure to copy ALL 
-- existing columns in source table, unless you want to remove
-- one or more columns
-- Note: CASTing an existing column as itself removes existing
-- type cast. This is necessary to make tables portable to other
-- databases. And these constraints no longer needed for analytical
-- database (e.g., "CAST(higher_plant_group AS TEXT) AS higher_plant_group")
DROP TABLE IF EXISTS :target_schema.view_full_occurrence_individual_dev;
CREATE TABLE :target_schema.view_full_occurrence_individual_dev AS 
SELECT 
taxonobservation_id,
CAST(NULL AS TEXT) AS observation_type,
CAST(NULL AS BIGINT) AS plot_metadata_id,
CAST(NULL AS BIGINT) AS datasource_id,
datasource,
CAST(NULL AS TEXT) AS dataset,
CAST(NULL AS TEXT) AS dataowner,
country,
state_province,
county,
locality,
latitude,
longitude,
coord_uncertainty_m,
CAST(georef_sources AS TEXT) AS georef_sources,
georef_protocol,
is_geovalid,
is_new_world,
project_id,
project_contributors,
location_id,
plot_name,
subplot,
is_location_cultivated,
locationevent_id,
event_date,
elevation_m,
slope_aspect_deg,
slope_gradient_deg,
plot_area_ha,
sampling_protocol,
temperature_c,
precip_mm,
stratum_name,
community_concept_name,
observation_contributors,
custodial_institution_codes,
collection_code,
catalog_number,
occurrence_id,
recorded_by,
record_number,
date_collected,
identified_by,
date_identified,
identification_remarks,
CAST(NULL AS BIGINT) AS bien_taxonomy_id,
verbatim_family,
verbatim_scientific_name,
CAST(NULL AS TEXT) AS name_submitted,
family_matched,
name_matched,
name_matched_author,
CAST(NULL AS TEXT) AS tnrs_warning,
taxonomic_status AS matched_taxonomic_status,
CAST(higher_plant_group AS TEXT) AS higher_plant_group,
scrubbed_family,
scrubbed_genus,
scrubbed_specific_epithet,
scrubbed_species_binomial,
scrubbed_taxon_name_no_author,
CAST(NULL AS TEXT) AS scrubbed_taxon_canonical,
scrubbed_author,
scrubbed_taxon_name_with_author,
scrubbed_species_binomial_with_morphospecies,
CAST(NULL AS TEXT) AS scrubbed_taxonomic_status,
CAST(growth_form AS TEXT) AS growth_form,
reproductive_condition,
is_cultivated,
is_cultivated_basis,
occurrence_remarks,
taxon_observation_id,
taxon_name_usage_concept_author_code,
plantobservation_id,
aggregate_organism_observation_id,
individual_organism_observation_id,
individual_id,
individual_count,
cover_percent,
CAST(NULL AS TEXT) AS cites,
CAST(NULL AS TEXT) AS iucn,
CAST(NULL AS TEXT) AS usda_federal,
CAST(NULL AS TEXT) AS usda_state,
CAST(NULL AS TEXT) AS is_embargoed_observation,
CAST(NULL AS geometry(Point,4326)) AS geom,
CAST(NULL AS BIGINT) AS nsr_id,
CAST(NULL AS TEXT) AS native_status_country,
CAST(NULL AS TEXT) AS native_status_state_province,
CAST(NULL AS TEXT) AS native_status_county_parish,
CAST(NULL AS TEXT) AS native_status,
CAST(NULL AS TEXT) AS native_status_reason,
CAST(NULL AS TEXT) AS native_status_sources,
CAST(NULL AS TEXT) AS isintroduced,
CAST(NULL AS TEXT) AS is_cultivated_in_region
FROM :src_schema.view_full_occurrence_individual
WHERE datasource IN (
'SALVIAS',
'FIA',
'CVS',
'VegBank',
'TEAM',
'Madidi'
)
LIMIT 500
;

INSERT INTO view_full_occurrence_individual_dev (
taxonobservation_id,
datasource,
country,
state_province,
county,
locality,
latitude,
longitude,
coord_uncertainty_m,
georef_protocol,
is_geovalid,
is_new_world,
project_id,
project_contributors,
location_id,
plot_name,
subplot,
is_location_cultivated,
locationevent_id,
event_date,
elevation_m,
slope_aspect_deg,
slope_gradient_deg,
plot_area_ha,
sampling_protocol,
temperature_c,
precip_mm,
stratum_name,
community_concept_name,
observation_contributors,
custodial_institution_codes,
collection_code,
catalog_number,
occurrence_id,
recorded_by,
record_number,
date_collected,
identified_by,
date_identified,
identification_remarks,
verbatim_family,
verbatim_scientific_name,
family_matched,
name_matched,
name_matched_author,
matched_taxonomic_status,
scrubbed_family,
scrubbed_genus,
scrubbed_specific_epithet,
scrubbed_species_binomial,
scrubbed_taxon_name_no_author,
scrubbed_author,
scrubbed_taxon_name_with_author,
scrubbed_species_binomial_with_morphospecies,
reproductive_condition,
is_cultivated,
is_cultivated_basis,
occurrence_remarks,
taxon_observation_id,
taxon_name_usage_concept_author_code,
plantobservation_id,
aggregate_organism_observation_id,
individual_organism_observation_id,
individual_id,
individual_count,
cover_percent
)
SELECT
taxonobservation_id,
datasource,
country,
state_province,
county,
locality,
latitude,
longitude,
coord_uncertainty_m,
georef_protocol,
is_geovalid,
is_new_world,
project_id,
project_contributors,
location_id,
plot_name,
subplot,
is_location_cultivated,
locationevent_id,
event_date,
elevation_m,
slope_aspect_deg,
slope_gradient_deg,
plot_area_ha,
sampling_protocol,
temperature_c,
precip_mm,
stratum_name,
community_concept_name,
observation_contributors,
custodial_institution_codes,
collection_code,
catalog_number,
occurrence_id,
recorded_by,
record_number,
date_collected,
identified_by,
date_identified,
identification_remarks,
verbatim_family,
verbatim_scientific_name,
family_matched,
name_matched,
name_matched_author,
taxonomic_status,
scrubbed_family,
scrubbed_genus,
scrubbed_specific_epithet,
scrubbed_species_binomial,
scrubbed_taxon_name_no_author,
scrubbed_author,
scrubbed_taxon_name_with_author,
scrubbed_species_binomial_with_morphospecies,
reproductive_condition,
is_cultivated,
is_cultivated_basis,
occurrence_remarks,
taxon_observation_id,
taxon_name_usage_concept_author_code,
plantobservation_id,
aggregate_organism_observation_id,
individual_organism_observation_id,
individual_id,
individual_count,
cover_percent
FROM :src_schema.view_full_occurrence_individual
WHERE datasource IN (
'GBIF',
'MO',
'REMIB',
'ARIZ'
)
LIMIT 500
;


-- Commit & release share lock on original table
COMMIT;