-- --------------------------------------------------------
-- Create raw trait data table
-- --------------------------------------------------------

set search_path to :sch;

-- Raw trait data table
DROP TABLE IF EXISTS :tbl_raw;
CREATE TABLE :tbl_raw (
"id" text default null,
"traits_id" text default null,
"verbatim_family" text default null,
"verbatim_scientific_name" text default null,
"name_submitted" text default null,
"family_matched" text default null,
"name_matched" text default null,
"name_matched_author" text default null,
"higher_plant_group" text default null,
"tnrs_warning" text default null,
"matched_taxonomic_status" text default null,
"scrubbed_taxonomic_status" text default null,
"scrubbed_family" text default null,
"scrubbed_genus" text default null,
"scrubbed_specific_epithet" text default null,
"scrubbed_species_binomial" text default null,
"scrubbed_taxon_name_no_author" text default null,
"scrubbed_taxon_canonical" text default null,
"scrubbed_author" text default null,
"scrubbed_taxon_name_with_author" text default null,
"scrubbed_species_binomial_with_morphospecies" text default null,
"trait_name" text default null,
"trait_value" text default null,
"unit" text default null,
"method" text default null,
"region" text default null,
"country" text default null,
"state_province" text default null,
"county" text default null,
"locality_description" text default null,
"latitude" text default null,
"min_latitude" text default null,
"max_latitude" text default null,
"longitude" text default null,
"min_longitude" text default null,
"max_longitude" text default null,
"elevation_m" text default null,
"source" text default null,
"url_source" text default null,
"source_citation" text default null,
"source_id" text default null,
"visiting_date" text default null,
"reference_number" text default null,
"access" text default null,
"project_pi" text default null,
"project_pi_contact" text default null,
"observation" text default null,
"authorship" text default null,
"authorship_contact" text default null,
"citation_bibtex" text default null,
"plant_trait_files" text default null,
"fk_tnrs_user_id" text default null,
"is_experiment" text default null,
"observation_context" text default null,
"observation_date" text default null,
"source_locality" text default null,
"is_individual_trait" text default null,
"is_species_trait" text default null,
"is_trait_value_valid" text default null,
"temporary_taxonobservation_id" text default null,
"taxonobservation_id" text default null,
"is_individual_measurement" text default null
);