-- --------------------------------------------------------
-- Creates main traits table
-- --------------------------------------------------------

set search_path to :sch;

-- Main trait table
DROP TABLE IF EXISTS agg_traits;
CREATE TABLE agg_traits (
id bigserial not null,
id_verbatim integer default null,
traits_id integer default null,
bien_taxonomy_id bigint,
taxon_id bigint,
family_taxon_id bigint,
genus_taxon_id bigint,
species_taxon_id bigint,
fk_tnrs_id bigint,
verbatim_family text,
verbatim_scientific_name text,
name_submitted text,
family_matched text,
name_matched text,
name_matched_author text,
tnrs_name_matched_score numeric(3,2),
higher_plant_group text,
tnrs_warning text,
matched_taxonomic_status text,
match_summary text,
scrubbed_taxonomic_status text,
scrubbed_family text,
scrubbed_genus text,
scrubbed_specific_epithet text,
scrubbed_species_binomial text,
scrubbed_taxon_name_no_author text,
scrubbed_taxon_canonical text,
scrubbed_author text,
scrubbed_taxon_name_with_author text,
scrubbed_species_binomial_with_morphospecies text,
trait_name text,
trait_value text,
unit text,
method text,
region text,
country_verbatim text,
state_province_verbatim text,
county_verbatim text,
poldiv_full text,
fk_gnrs_id bigint,
country character varying(250),
state_province character varying(250),
county character varying(250),
fk_centroid_id bigint,
is_centroid smallint,
centroid_likelihood numeric,
centroid_poldiv text,
centroid_type text,
is_in_country smallint,
is_in_state_province smallint,
is_in_county smallint,
locality_description text,
latlong_verbatim text,
latitude numeric,
min_latitude numeric,
max_latitude numeric,
longitude numeric,
min_longitude numeric,
max_longitude numeric,
coord_uncertainty_verbatim text,
coord_max_uncertainty_km numeric,
georef_sources text,
georef_protocol text,
is_geovalid smallint,
geovalid_failed_reason text,
geom postgis.geometry(Point,4326) default null,
is_new_world smallint,
elevation_verbatim text,
elevation_m integer,
elevation_min_m integer,
elevation_max_m integer,
source text,
url_source text,
source_citation text,
source_id text,
visiting_date_verbatim text,
visiting_date date,
visiting_date_accuracy text,
reference_number text,
access text,
project_pi text,
project_pi_contact text,
observation text,
authorship text,
authorship_contact text,
citation_bibtex text,
plant_trait_files text,
is_experiment smallint,
observation_context text,
observation_date_verbatim text,
observation_date date,
observation_date_accuracy text,
source_locality text,
is_individual_trait smallint,
is_species_trait smallint,
is_trait_value_valid smallint,
temporary_taxonobservation_id text,
taxonobservation_id bigint,
is_individual_measurement smallint,
is_embargoed_observation smallint,
nsr_id bigint,
native_status_country text,
native_status_state_province text,
native_status_county_parish text,
native_status text,
native_status_reason text,
native_status_sources text,
isintroduced smallint,
is_cultivated_in_region smallint,
is_cultivated_taxon smallint,
is_cultivated_observation smallint,
is_cultivated_observation_basis smallint
);

