--
-- Drop all indexes on analytical_stem_dev
--

SET search_path TO :sch;

-- Drop PK
-- Must drop constraints first, if any
ALTER TABLE analytical_stem_dev DROP CONSTRAINT IF EXISTS astem_pkey;
ALTER TABLE analytical_stem_dev DROP CONSTRAINT IF EXISTS analytical_stem_dev_pkey;
ALTER TABLE analytical_stem_dev DROP CONSTRAINT IF EXISTS analytical_stem_pkey;
DROP INDEX IF EXISTS astem_pkey;
DROP INDEX IF EXISTS analytical_stem_dev_pkey;
DROP INDEX IF EXISTS analytical_stem_pkey;

-- Drop remaining indexes
DROP INDEX IF EXISTS analytical_stem_dev_pkey;
DROP INDEX IF EXISTS analytical_stem_dev_taxonobservation_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_plot_metadata_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_datasource_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_datasource_idx;
DROP INDEX IF EXISTS analytical_stem_dev_dataset_idx;
DROP INDEX IF EXISTS analytical_stem_dev_fk_gnrs_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_country_idx;
DROP INDEX IF EXISTS analytical_stem_dev_country_state_province_idx;
DROP INDEX IF EXISTS analytical_stem_dev_country_state_province_county_idx;
DROP INDEX IF EXISTS analytical_stem_dev_lat_long_not_null_idx;
DROP INDEX IF EXISTS analytical_stem_dev_fk_centroid_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_in_country_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_in_state_province_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_in_county_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_geovalid_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_new_world_idx;
DROP INDEX IF EXISTS analytical_stem_dev_plot_name_idx;
DROP INDEX IF EXISTS analytical_stem_dev_plot_name_subplot_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_location_cultivated_idx;
DROP INDEX IF EXISTS analytical_stem_dev_event_date_idx;
DROP INDEX IF EXISTS analytical_stem_dev_event_date_accuracy_idx;
DROP INDEX IF EXISTS analytical_stem_dev_elevation_m_idx;
DROP INDEX IF EXISTS analytical_stem_dev_plot_area_ha_idx;
DROP INDEX IF EXISTS analytical_stem_dev_sampling_protocol_idx;
DROP INDEX IF EXISTS analytical_stem_dev_vegetation_verbatim_idx;
DROP INDEX IF EXISTS analytical_stem_dev_community_concept_name_idx;
DROP INDEX IF EXISTS analytical_stem_dev_catalog_number_idx;
DROP INDEX IF EXISTS analytical_stem_dev_recorded_by_idx;
DROP INDEX IF EXISTS analytical_stem_dev_record_number_idx;
DROP INDEX IF EXISTS analytical_stem_dev_date_collected_idx;
DROP INDEX IF EXISTS analytical_stem_dev_date_collected_accuracy_idx;
DROP INDEX IF EXISTS analytical_stem_dev_identified_by_idx;
DROP INDEX IF EXISTS analytical_stem_dev_bien_taxonomy_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_family_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_genus_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_species_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_verbatim_scientific_name_idx;
DROP INDEX IF EXISTS analytical_stem_dev_fk_tnrs_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_family_matched_idx;
DROP INDEX IF EXISTS analytical_stem_dev_name_matched_idx;
DROP INDEX IF EXISTS analytical_stem_dev_matched_taxonomic_status_idx;
DROP INDEX IF EXISTS analytical_stem_dev_match_summary_idx;
DROP INDEX IF EXISTS analytical_stem_dev_scrubbed_taxonomic_status_idx;
DROP INDEX IF EXISTS analytical_stem_dev_higher_plant_group_idx;
DROP INDEX IF EXISTS analytical_stem_dev_scrubbed_family_idx;
DROP INDEX IF EXISTS analytical_stem_dev_scrubbed_genus_idx;
DROP INDEX IF EXISTS analytical_stem_dev_scrubbed_species_binomial_idx;
DROP INDEX IF EXISTS analytical_stem_dev_scrubbed_taxon_name_no_author_idx;
DROP INDEX IF EXISTS analytical_stem_dev_scrubbed_species_binomial_with_morphospecies_idx;
DROP INDEX IF EXISTS analytical_stem_dev_growth_form_idx;
DROP INDEX IF EXISTS analytical_stem_dev_reproductive_condition_idx;
DROP INDEX IF EXISTS analytical_stem_dev_individual_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_cites_idx;
DROP INDEX IF EXISTS analytical_stem_dev_iucn_idx;
DROP INDEX IF EXISTS analytical_stem_dev_usda_federal_idx;
DROP INDEX IF EXISTS analytical_stem_dev_usda_state_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_embargoed_observation_idx;
DROP INDEX IF EXISTS analytical_stem_dev_nsr_id_idx;
DROP INDEX IF EXISTS analytical_stem_dev_native_status_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_introduced_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_cultivated_in_region_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_cultivated_taxon_idx;
DROP INDEX IF EXISTS analytical_stem_dev_is_cultivated_observation_idx;
DROP INDEX IF EXISTS analytical_stem_dev_validated_species_idx;
DROP INDEX IF EXISTS analytical_stem_dev_latlong_verbatim_idx;

-- Without _dev suffix
DROP INDEX IF EXISTS analytical_stem_pkey;
DROP INDEX IF EXISTS analytical_stem_taxonobservation_id_idx;
DROP INDEX IF EXISTS analytical_stem_plot_metadata_id_idx;
DROP INDEX IF EXISTS analytical_stem_datasource_id_idx;
DROP INDEX IF EXISTS analytical_stem_datasource_idx;
DROP INDEX IF EXISTS analytical_stem_dataset_idx;
DROP INDEX IF EXISTS analytical_stem_fk_gnrs_id_idx;
DROP INDEX IF EXISTS analytical_stem_country_idx;
DROP INDEX IF EXISTS analytical_stem_country_state_province_idx;
DROP INDEX IF EXISTS analytical_stem_country_state_province_county_idx;
DROP INDEX IF EXISTS analytical_stem_lat_long_not_null_idx;
DROP INDEX IF EXISTS analytical_stem_fk_centroid_id_idx;
DROP INDEX IF EXISTS analytical_stem_is_in_country_idx;
DROP INDEX IF EXISTS analytical_stem_is_in_state_province_idx;
DROP INDEX IF EXISTS analytical_stem_is_in_county_idx;
DROP INDEX IF EXISTS analytical_stem_is_geovalid_idx;
DROP INDEX IF EXISTS analytical_stem_is_new_world_idx;
DROP INDEX IF EXISTS analytical_stem_plot_name_idx;
DROP INDEX IF EXISTS analytical_stem_plot_name_subplot_idx;
DROP INDEX IF EXISTS analytical_stem_is_location_cultivated_idx;
DROP INDEX IF EXISTS analytical_stem_event_date_idx;
DROP INDEX IF EXISTS analytical_stem_event_date_accuracy_idx;
DROP INDEX IF EXISTS analytical_stem_elevation_m_idx;
DROP INDEX IF EXISTS analytical_stem_plot_area_ha_idx;
DROP INDEX IF EXISTS analytical_stem_sampling_protocol_idx;
DROP INDEX IF EXISTS analytical_stem_vegetation_verbatim_idx;
DROP INDEX IF EXISTS analytical_stem_community_concept_name_idx;
DROP INDEX IF EXISTS analytical_stem_catalog_number_idx;
DROP INDEX IF EXISTS analytical_stem_recorded_by_idx;
DROP INDEX IF EXISTS analytical_stem_record_number_idx;
DROP INDEX IF EXISTS analytical_stem_date_collected_idx;
DROP INDEX IF EXISTS analytical_stem_date_collected_accuracy_idx;
DROP INDEX IF EXISTS analytical_stem_identified_by_idx;
DROP INDEX IF EXISTS analytical_stem_bien_taxonomy_id_idx;
DROP INDEX IF EXISTS analytical_stem_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_family_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_genus_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_species_taxon_id_idx;
DROP INDEX IF EXISTS analytical_stem_verbatim_scientific_name_idx;
DROP INDEX IF EXISTS analytical_stem_fk_tnrs_id_idx;
DROP INDEX IF EXISTS analytical_stem_family_matched_idx;
DROP INDEX IF EXISTS analytical_stem_name_matched_idx;
DROP INDEX IF EXISTS analytical_stem_matched_taxonomic_status_idx;
DROP INDEX IF EXISTS analytical_stem_match_summary_idx;
DROP INDEX IF EXISTS analytical_stem_scrubbed_taxonomic_status_idx;
DROP INDEX IF EXISTS analytical_stem_higher_plant_group_idx;
DROP INDEX IF EXISTS analytical_stem_scrubbed_family_idx;
DROP INDEX IF EXISTS analytical_stem_scrubbed_genus_idx;
DROP INDEX IF EXISTS analytical_stem_scrubbed_species_binomial_idx;
DROP INDEX IF EXISTS analytical_stem_scrubbed_taxon_name_no_author_idx;
DROP INDEX IF EXISTS analytical_stem_scrubbed_species_binomial_with_morphospecies_idx;
DROP INDEX IF EXISTS analytical_stem_growth_form_idx;
DROP INDEX IF EXISTS analytical_stem_reproductive_condition_idx;
DROP INDEX IF EXISTS analytical_stem_individual_id_idx;
DROP INDEX IF EXISTS analytical_stem_cites_idx;
DROP INDEX IF EXISTS analytical_stem_iucn_idx;
DROP INDEX IF EXISTS analytical_stem_usda_federal_idx;
DROP INDEX IF EXISTS analytical_stem_usda_state_idx;
DROP INDEX IF EXISTS analytical_stem_is_embargoed_observation_idx;
DROP INDEX IF EXISTS analytical_stem_nsr_id_idx;
DROP INDEX IF EXISTS analytical_stem_native_status_idx;
DROP INDEX IF EXISTS analytical_stem_is_introduced_idx;
DROP INDEX IF EXISTS analytical_stem_is_cultivated_in_region_idx;
DROP INDEX IF EXISTS analytical_stem_is_cultivated_taxon_idx;
DROP INDEX IF EXISTS analytical_stem_is_cultivated_observation_idx;
DROP INDEX IF EXISTS analytical_stem_validated_species_idx;
DROP INDEX IF EXISTS analytical_stem_latlong_verbatim_idx;
